{
    "name": "julyclient",
    "version": "0.1.0",
    "private": true,
    "scripts": {
        "deploy": "npm run build &&  rsync --exclude=.git -azP . ubuntu@3.98.5.128:/home/ubuntu/apps/next-amazona",
        "dev": "next dev",
        "build": "next build",
        "start": "next start",
        "lint": "next lint",
        "postbuild": "next-sitemap --config next-sitemap.js",
        "sitemap": "next-sitemap"
    },
    "dependencies": {
        "@headlessui/react": "^1.7.18",
        "@paypal/react-paypal-js": "^8.1.3",
        "@tinymce/tinymce-react": "^4.3.0",
        "axios": "^1.6.7",
        "bcryptjs": "^2.4.3",
        "chart.js": "^4.4.1",
        "cloudinary": "^2.0.1",
        "dotenv": "^16.3.1",
        "framer-motion": "^10.12.18",
        "html-react-parser": "^3.0.16",
        "isomorphic-dompurify": "^1.3.0",
        "js-cookie": "^3.0.5",
        "mailgun-js": "^0.22.0",
        "moment": "^2.29.4",
        "mongoose": "^8.1.3",
        "mongoose-slug-generator": "^1.0.4",
        "next": "14.1.0",
        "next-auth": "^4.24.6",
        "next-sitemap": "^4.2.2",
        "react": "18.2.0",
        "react-chartjs-2": "^5.2.0",
        "react-datepicker": "^7.6.0",
        "react-dom": "18.2.0",
        "react-hook-form": "^7.50.1",
        "react-icons": "^4.11.0",
        "react-ios-time-picker": "^0.2.2",
        "react-mailchimp-subscribe": "^2.1.3",
        "react-multi-carousel": "^2.8.5",
        "react-responsive-carousel": "^3.2.23",
        "react-scroll": "^1.9.0",
        "react-time-picker": "^7.0.0",
        "react-toastify": "^10.0.4",
        "sharp": "^0.33.4",
        "swiper": "^8.3.2",
        "tinymce": "^6.4.1"
    },
    "devDependencies": {
        "@heroicons/react": "^2.1.5",
        "@types/react": "^18.2.57",
        "autoprefixer": "^10.4.17",
        "eslint": "8.56.0",
        "eslint-config-next": "14.1.0",
        "postcss": "^8.4.35",
        "tailwindcss": "^3.4.1"
    }
}
